BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Category" (
	"_id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"categoryName"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "ExpensesCategories" (
	"_id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"ExpenseName"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "Currency" (
	"_id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"CurrencyName"	TEXT NOT NULL
);
COMMIT;
